### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Athena112233** [MIDS-at-Duke/uds-2022-ids-701-team-7#1]
### Data Gathering
 - [x] Climate data divided by states (Athena and Abhi)
 - [x] Energy price data (Tianyun and Weiliang)
 - [ ] Decide what states to focus on

### Data Cleaning and Preprocessing
 - [x] Data merge 
 - [x] Check for missing/duplicate values
 - [x] Convert energy generation into percentage
 - [ ] Create indicator variable for RPS
 - [ ] Normalization/scaling/grouping data 

### EDA/Assumption Checking
- [ ] check distribution
- [ ] check balance/assumptions

### Analysis
- [ ] modeling? interpretation

### Report
- [ ] TBD
